name: Manager Workflow
on: [push]

jobs:
  call-printer:
    # Use the local path to the file you just created
    uses: ./.github/workflows/printer.yml
    with:
      user_name: "mak"
    secrets:
      api_key: ${{ secrets.MY_PASSWORD }}

  results:
    needs: call-printer
    runs-on: ubuntu-latest
    steps:
      - run: echo "The template says ${{ needs.call-printer.outputs.job_status }}"