name : multi-line command
on : push
jobs :
  multi_line_job :
    runs-on: ubuntu-latest
    steps:

    - name : checkout
      uses : actions/checkout@v4

    - name : multi-line command pass
      run : |
        echo "Hello World !!"
        ls -ltr
        cat README.md