name: Main Project App

on:
  push:
    branches: [main]

jobs:
  call-simple-task:
    # Syntax: {owner}/{repo}/{path}/{file}@{ref}

    uses: mukeshdas088/test-github/.github/workflows/simple-hello.yml@main