name: Simple Reusable Workflow

on:
  workflow_call: # This makes it reusable

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple script
        run: echo "This is a standardized task running without any extra parameters!"