name: Test Composite Action

on: 
  workflow_dispatch:
    inputs:
      user-name:
        description: 'Select a user to greet'
        required: true
        default: 'Mukesh'
        type: choice
        options:
          - 'Mukesh'
          - 'Admin'
          - 'Guest'
          - 'Developer'

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run My Action
        uses: ./.github/actions/my-custom-action
        with:
          # This passes the selected option from the UI to your action
          user-name: ${{ github.event.inputs.user-name }}